services:
  - type: web
    name: sampleproject-fullstack
    env: node
    plan: free
    buildCommand: npm install && cd server && npm install && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: MASTER_DB_URI
        sync: false
      - key: TENANT_DB_BASE_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: VITE_API_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FAST2SMS_API_KEY
        sync: false
